class ErrorCodes:
    BOOK_NOT_FOUND = "BOOK_NOT_FOUND"
    MEMBER_NOT_FOUND = "MEMBER_NOT_FOUND"
    BOOK_ALREADY_BORROWED = "BOOK_ALREADY_BORROWED"
    BOOK_NOT_BORROWED = "BOOK_NOT_BORROWED"
    BOOK_NOT_BORROWED_BY_MEMBER = "BOOK_NOT_BORROWED_BY_MEMBER"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    INVALID_INPUT = "INVALID_INPUT"